### ISSUE TITLE
Add proper collapsed by default behaviour

### ISSUE THREAD

**Issue by KittyGiraudel** [edenspiekermann/a11y-toggle#21]

**Comment by KittyGiraudel** [comment]
So, regarding this issue…

## The problem

The problem right now is that it is not quite obvious how to have a “collapsed by default” behaviour. As of today, you would do it by adding the required attributes manually:

``` html
<button type="button" data-a11y-toggle="foo" aria-expanded="false">Toggle</button>
<div id="foo" aria-hidden="true">Content</div>
```

It is not quite obvious but as long as it is documented, I would argue that is fine. However, it causes an issue with AT users that have JavaScript disabled, because they end up with hidden content without a way to access it.

## The solution

It means we need to extend the DOM API to make it possible to declare a toggle/target combo as collapsed by default and let the JavaScript layer adds all the required attributes.

I believe the collapsed by default state should also be the default as it is a much more common use case than having displayed content that you can collapse. Users perform an action to display more content, not less. At least that seems like a reasonable assumption.

Which means we have a few options for the API:
- `data-a11y-toggle-state="collapsed"` /  `data-a11y-toggle-state="expanded"`
- `data-a11y-toggle-collapsed` /  `data-a11y-toggle-expanded`
- `data-a11y-toggle-state="closed"` /  `data-a11y-toggle-state="open"`
- `data-a11y-toggle-closed` /  `data-a11y-toggle-open`
- `data-a11y-toggle-open="true"` /  `data-a11y-toggle-open="false"`
- `data-a11y-toggle-closed="true"` /  `data-a11y-toggle-closed="false"`
- `data-a11y-toggle-expanded="true"` /  `data-a11y-toggle-expanded="false"`
- `data-a11y-toggle-collapsed="true"` /  `data-a11y-toggle-collapsed="false"`
- Anything else?

@edenspiekermann/js @edenspiekermann/css I’d love opinion on this topic. Pretty please?

**Comment by smartmike** [comment]
As I said yesterday I think something as simple as `data-a11y-toggle-open="true"` or `data-a11y-toggle-open="false"` – with false being the default.

**Comment by KittyGiraudel** [comment]
@smartmike We have to use `-toggle` in the data-attribute to avoid any conflict with possible other a11y libraries. But I hear your point.

**Comment by peterjmag** [comment]
Note that [empty data attributes are valid](http://stackoverflow.com/a/9729132/349353), so it could be as simple as `data-a11y-toggle-open`. `closed` isn't really necessary, since it's the default state. That would also have the advantage of lining up with the API for [the `<details>` element](https://developer.mozilla.org/en/docs/Web/HTML/Element/details#Attributes):

_Closed by default_

``` html
<details>
  [...]
</details>
```

_Open by default_

``` html
<details open>
  [...]
</details>
```

**Comment by KittyGiraudel** [comment]
Strong point.

**Comment by smartmike** [comment]
Very good point.

**Comment by KittyGiraudel** [comment]
How would you deal with `data-a11y-toggle-open="false"`? Treated as open or closed?

**Comment by smartmike** [comment]
Closed. Just in case people feel the need to explicitly define it.

**Comment by peterjmag** [comment]
Hmm, well unfortunately `open="false"` still gets interpreted as "open", due to [how boolean attributes are specified](http://stackoverflow.com/a/32745315/349353). See http://codepen.io/peterjmag/pen/BKrgNy for some examples.

So I'd recommend using the same behavior, but simply documenting that an empty `data-a11y-toggle-open` attribute is the accepted / "valid" way to change the default behavior.

**Comment by smartmike** [comment]
Sounds good

**Comment by KittyGiraudel** [comment]
Okay, thank you for your opinion. That should give me enough to implement V2. :)

**Comment by KittyGiraudel** [comment]
Done in 2.0.0.
